lsi: false
safe: true
source: /frontend
exclude:
- node_modules
- /frontend/node_modules
- frontend/node_modules
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
