#steps:
#- name: "gcr.io/cloud-builders/gcloud"
#  args: ["app", "deploy"]
#timeout: "2000s"

steps:
- name: python
  entrypoint: pip
  args: ["install", "-r", "backend/requirements.txt", "--user"]
- name: python
  entrypoint: python
  args: ["-m", "pytest", "--junitxml=${SHORT_SHA}_test_log.xml"]   
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/$PROJECT_ID/angular-nginx-container', 'frontend/nginx-hosting']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'backend/app.yaml'] 
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/$PROJECT_ID/angular-nginx-container']
- name: "gcr.io/cloud-builders/gcloud"
  args: ['app', 'deploy', 'frontend/nginx-hosting/app.yaml'] 
images: ['us.gcr.io/$PROJECT_ID/angular-nginx-container']
timeout: "2000s"

options:
  logging: CLOUD_LOGGING_ONLY
